name: SimpleCloud-Sign
version: 1.0
author: Wetterbericht

main: eu.thesimplecloud.module.sign.service.BukkitPluginMain

depend: [SimpleCloud-Plugin]

commands:
  cloudsigns:
    permission: cloud.command.signs
