name: SimpleCloud-Permission
version: 1.0
author: Wetterbericht
folia-supported: true

main: eu.thesimplecloud.module.permission.service.spigot.SpigotPluginMain

depend: [SimpleCloud-Plugin]

api-version: 1.13

commands:
